### ISSUE TITLE
Cannot send pictures

### ISSUE THREAD

**Issue by javifloresi** [stonesam92/WhatsMac#7]
1.0.0 on Yosemite 10.10.3, upload picture button do nothing

**Comment by stonesam92** [comment]
Yeah, this is addressed in the ReadMe. `WKWebView` doesn't work well with `<input type="file">` tags, so that button doesn't work until I can think of a workaround. 

Dragging and dropping an image file onto the window works, though. 

Until a proper solution can be found, I will make changes so that when a user clicks the button an alert is shown advising them to use the drag-and-drop method to upload media.

**Comment by stonesam92** [comment]
As of 6d24c31449d1666244b844b3821ca5170c43bac3, an alert is presented when that button is clicked informing the user to drag-n-drop files to upload media.
